### ISSUE TITLE
Uncaught Error: EACCES, permission denied '/etc/apt/sources.list.d/pgdg.list'

### ISSUE THREAD

**Issue by AlexSYanai** [atom/autosave#27]
Uncaught Error: EACCES, permission denied '/etc/apt/sources.list.d/pgdg.list'

**Atom Version**: 0.158.0
**System**: linux 3.13.0-44-generic
**Thrown From**: [autosave](https://github.com/atom/autosave) package, v0.19.0

### Steps To Reproduce

1. ...
2. ...

### Stack Trace

```
At /usr/share/atom/resources/app/node_modules/pathwatcher/lib/file.js:311

Error: EACCES, permission denied '/etc/apt/sources.list.d/pgdg.list'
  at Error (native)
  at Object.fs.openSync (fs.js:455:18)
  at Object.module.(anonymous function) [as openSync] (/usr/share/atom/resources/atom/common/lib/asar.js:422:20)
  at Object.fs.writeFileSync (fs.js:1011:15)
  at Object.fsPlus.writeFileSync (/usr/share/atom/resources/app/node_modules/fs-plus/lib/fs-plus.js:228:17)
  at File.module.exports.File.writeFileSync (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/file.js:227:19)
  at File.module.exports.File.writeFileWithPrivilegeEscalationSync (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/file.js:297:21)
  at File.module.exports.File.write (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/file.js:286:12)
  at TextBuffer.module.exports.TextBuffer.saveAs (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:966:17)
  at TextBuffer.module.exports.TextBuffer.save (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:954:19)
  at TextEditor.module.exports.TextEditor.save (/usr/share/atom/resources/app/src/text-editor.js:585:26)
  at Object.module.exports.autosavePaneItem (/usr/share/atom/resources/app/node_modules/autosave/lib/autosave.js:56:80)
  at /usr/share/atom/resources/app/node_modules/autosave/lib/autosave.js:27:26
  at HTMLInputElement.<anonymous> (/usr/share/atom/resources/app/src/text-editor-element.js:178:26)

```

/cc @atom/core

**Comment by 50Wliu** [comment]
Please upgrade Atom to the latest version-this has been fixed.
