### ISSUE TITLE
Uncaught Error: dlopen(/Users/spawas/Downloads/Atom.app/Contents/Resources/app.asar.unpacked/node...

### ISSUE THREAD

**Issue by spawashe** [atom/autosave#55]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Mac OS X 10.10.5
**Thrown From**: [autosave](https://github.com/atom/autosave) package, v0.23.0
### Stack Trace

Uncaught Error: dlopen(/Users/spawas/Downloads/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/runas/build/Release/runas.node, 1): image not found

```
At /Users/spawas/Downloads/Atom.app/Contents/Resources/app.asar/src/pane.js:825

Error: dlopen(/Users/spawas/Downloads/Atom.app/Contents/Resources/app.asar.unpacked/node_modules/runas/build/Release/runas.node, 1): image not found
    at Error (native)
    at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:137:20)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:148:18)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/spawas/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/runas/lib/runas.js:4:11)
    at Object.<anonymous> (/Users/spawas/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/runas/lib/runas.js:47:4)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/Users/spawas/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at File.module.exports.File.writeFileWithPrivilegeEscalationSync (/Users/spawas/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/file.js:403:21)
    at File.module.exports.File.writeSync (/Users/spawas/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/pathwatcher/lib/file.js:355:12)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Users/spawas/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1021:19)
    at TextBuffer.module.exports.TextBuffer.save (/Users/spawas/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1002:19)
    at TextEditor.module.exports.TextEditor.save (/Users/spawas/Downloads/Atom.app/Contents/Resources/app.asar/src/text-editor.js:557:26)
    at Pane.module.exports.Pane.saveItem (/Users/spawas/Downloads/Atom.app/Contents/Resources/app.asar/src/pane.js:530:18)
    at Object.module.exports.autosavePaneItem (/Users/spawas/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/autosave/lib/autosave.js:64:21)
    at /Users/spawas/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/autosave/lib/autosave.js:29:26
```
### Commands

```
     -1:06.4.0 vim-mode:activate-insert-mode (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -1:00.1.0 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:57.5.0 core:move-left (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  2x -0:52.8.0 core:undo (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:50.1.0 core:move-right (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  3x -0:49.7.0 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:23.8.0 core:undo (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:16.8.0 window:save-all (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  4x -0:02.2.0 blur (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
```
### Config

``` json
{
  "core": {},
  "autosave": {
    "enabled": true
  }
}
```
### Installed Packages

``` coffee
# User
No installed packages

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
Hi @spawashe, can you please share what you were doing when this error occurred?  Thanks!
