### ISSUE TITLE
Failed to load the autosave package

### ISSUE THREAD

**Issue by graemelambert** [atom/autosave#62]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.6.0
**System**: Mac OS X 10.10.2
**Thrown From**: [autosave](https://github.com/atom/autosave) package, v0.23.1

### Stack Trace

Failed to load the autosave package

```
At Cannot find module 'fs-plus'

Error: Cannot find module 'fs-plus'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Users/graeme.lambert/Downloads/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Users/graeme.lambert/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/graeme.lambert/.atom/packages/autosave/lib/autosave.coffee:2:6)
    at Object.<anonymous> (/Users/graeme.lambert/.atom/packages/autosave/lib/autosave.coffee:1:1)
    at Module._compile (/Users/graeme.lambert/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Users/graeme.lambert/Downloads/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/graeme.lambert/Downloads/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Users/graeme.lambert/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:720:27)
    at /Users/graeme.lambert/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:116:28
    at Package.module.exports.Package.measure (/Users/graeme.lambert/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/Users/graeme.lambert/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/Users/graeme.lambert/Downloads/Atom.app/Contents/Resources/app.asar/src/package-manager.js:445:14)
    at PackageManager.module.exports.PackageManager.loadPackages (/Users/graeme.lambert/Downloads/Atom.app/Contents/Resources/app.asar/src/package-manager.js:395:14)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/Users/graeme.lambert/Downloads/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:684:21)
    at module.exports (/Users/graeme.lambert/Downloads/Atom.app/Contents/Resources/app.asar/src/initialize-application-window.js:28:10)
    at setupWindow (file:///Users/graeme.lambert/Downloads/Atom.app/Contents/Resources/app.asar/static/index.js:86:5)
    at window.onload (file:///Users/graeme.lambert/Downloads/Atom.app/Contents/Resources/app.asar/static/index.js:41:9)
```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
autosave, v0.23.1
event-kit, v2.0.0
fs-plus, v2.8.1
nuclide, v0.125.0
php-hyperclick, v0.3.1

# Dev
No dev packages
```

**Comment by thomasjo** [comment]
How did you install the package? If you cloned the repository manually, you have to execute `apm install` from the cloned root directory.

**Comment by thomasjo** [comment]
By the way, it looks like something has gone horribly wrong with your setup; both `event-kit` and `fs-plus` are npm packages, and should **not** show up in the package list.

**Comment by graemelambert** [comment]
Sorry, **_npm install_** was all that was required.

**Comment by 50Wliu** [comment]
@graemelambert A bit late to this issue, but please use `apm install` next time instead of `npm install`.  The two have subtle differences that may cause a package to break when installed using `npm`.
