### ISSUE TITLE
Uncaught Error: Can't create a backup file for /Users/djtouchette/work/MichaelWolfe/panelHandicap...

### ISSUE THREAD

**Issue by DJTouchette** [atom/autosave#68]
[Enter steps to reproduce below:]

1. Editing package.json
2. Happen to be using https://github.com/mxstbr/react-boilerplate
3. package.json is saved multiple times

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.6
**Thrown From**: [autosave](https://github.com/atom/autosave) package, v0.23.1

### Stack Trace

Uncaught Error: Can't create a backup file for /Users/djtouchette/work/MichaelWolfe/panelHandicappers/package.json because files already exist at every candidate path.

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:1002

Error: Can't create a backup file for /Users/djtouchette/work/MichaelWolfe/panelHandicappers/package.json because files already exist at every candidate path.
    at TextBuffer.module.exports.TextBuffer.backUpFileContentsBeforeWriting (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1169:17)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1096:31)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1083:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:660:26)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:718:18)
    at Object.module.exports.autosavePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autosave/lib/autosave.js:58:21)
    at Object.module.exports.autosaveAllPaneItems (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autosave/lib/autosave.js:69:28)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autosave/lib/autosave.js:21:26
```

### Commands

```
  4x -1:19.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:09.8.0 core:move-left (atom-text-editor.editor.is-focused)
 22x -1:08.9.0 core:move-right (atom-text-editor.editor.is-focused)
  3x -1:06.2.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:56.4.0 core:save (atom-text-editor.editor.is-focused)
     -0:47.3.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:47 core:backspace (atom-text-editor.editor.is-focused)
     -0:46 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
 12x -0:45.7.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:43.1.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:39.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:35.4.0 core:paste (atom-text-editor.editor.is-focused)
     -0:29.2.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:27.2.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
  4x -0:24.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:20.5.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "highlight-line",
      "save-session",
      "file-type-icons",
      "vim-mode-plus",
      "vim-mode",
      "angularjs",
      "autocomplete-angular-material",
      "npm-docs"
    ],
    "themes": [
      "flexible-ui",
      "solarized-dark-syntax"
    ]
  },
  "autosave": {
    "enabled": true
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.5.1
angular-2-typeScript-snippets, v0.4.6
api-docs, v0.0.5
atom-ternjs, v0.14.2
atom-typescript, v10.1.4
autoclose-html, v0.23.0
autocomplete-ruby, v0.1.0
color-picker, v2.2.2
emmet, v2.4.3
file-icon-supplement, v0.8.3
flexible-ui, v0.10.3
highlight-selected, v0.11.2
language-javascript-jsx, v0.3.7
linter, v1.11.14
linter-jade, v0.3.2
linter-jshint, v2.1.0
linter-ruby, v1.2.2
merge-conflicts, v1.4.4
rails-finder, v0.7.0
rails-i18n-autocomplete, v0.4.0
save-notification, v0.10.0
terminal-plus, v0.14.5
tree-view-git-branch, v0.1.2
webbox-color, v0.5.9

# Dev
No dev packages
```

**Comment by JacopoGobbi** [comment]
I got this problem too and it keeps showing from few minutes ago :(
