### ISSUE TITLE
Uncaught ReferenceError: error is not defined

### ISSUE THREAD

**Issue by bovkun** [atom/autosave#69]
**Atom Version**: 1.9.8
**System**: Unknown Windows Version
**Thrown From**: [autosave](https://github.com/atom/autosave) package, v0.23.1

### Stack Trace

Uncaught ReferenceError: error is not defined

```
At C:\Users\A\AppData\Local\atom\app-1.9.8\resources\app.asar\src\pane.js:1026

ReferenceError: error is not defined
    at File.module.exports.File.safeRemoveSync (C:\Users\A\AppData\Local\atom\app-1.9.8\resources\app.asar\node_modules\text-buffer\node_modules\pathwatcher\lib\file.js:503:17)
    at TextBuffer.module.exports.TextBuffer.saveAs (C:\Users\A\AppData\Local\atom\app-1.9.8\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1144:22)
    at TextBuffer.module.exports.TextBuffer.save (C:\Users\A\AppData\Local\atom\app-1.9.8\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1126:19)
    at TextEditor.module.exports.TextEditor.save (C:\Users\A\AppData\Local\atom\app-1.9.8\resources\app.asar\src\text-editor.js:743:26)
    at Pane.module.exports.Pane.saveItem (C:\Users\A\AppData\Local\atom\app-1.9.8\resources\app.asar\src\pane.js:734:18)
    at Pane.saveItem (C:\Users\A\AppData\Local\atom\app-1.9.8\resources\app.asar\src\pane.js:3:61)
    at Object.module.exports.autosavePaneItem (C:\Users\A\AppData\Local\atom\app-1.9.8\resources\app.asar\node_modules\autosave\lib\autosave.js:58:21)
    at C:\Users\A\AppData\Local\atom\app-1.9.8\resources\app.asar\node_modules\autosave\lib\autosave.js:23:26
```

### Commands

```
     -1:46.7.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:46.1.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -1:46.1.0 snippets:expand (atom-text-editor.editor.is-focused)
     -1:41.2.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:39.6.0 core:move-left (atom-text-editor.editor.is-focused)
     -1:38.1.0 bracket-matcher:go-to-matching-bracket (atom-text-editor.editor.is-focused)
  3x -0:45.9.0 core:copy (atom-text-editor.editor.is-focused)
     -0:42 core:paste (atom-text-editor.editor.is-focused)
     -0:30 core:copy (atom-text-editor.editor.is-focused)
  2x -0:27.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:25.9.0 core:paste (atom-text-editor.editor.is-focused)
     -0:24.7.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -0:18.2.0 core:copy (atom-text-editor.editor.is-focused)
     -0:07.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:06.9.0 core:paste (atom-text-editor.editor.is-focused)
  2x -0:05.4.0 editor:newline (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "seti-icons",
      "sync-settings",
      "less-build",
      "atom-less",
      "language-perl",
      "language-yaml",
      "language-toml",
      "language-shellscript",
      "language-sass",
      "language-ruby-on-rails",
      "language-ruby",
      "language-python",
      "language-objective-c",
      "language-mustache",
      "language-make",
      "language-go",
      "language-c",
      "language-clojure",
      "language-csharp",
      "language-java",
      "linter-csslint",
      "minimap-highlight-selected",
      "metrics",
      "styleguide",
      "welcome",
      "atom-idle-autosave",
      "autocomplete-snippets",
      "autocomplete-php"
    ],
    "packagesWithKeymapsDisabled": [],
    "themes": [
      "atom-material-ui",
      "chester-atom-syntax"
    ]
  },
  "autosave": {
    "enabled": true
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.29.10 (active)
atom-idle-autosave, v0.3.0 (inactive)
atom-less, v0.1.10 (inactive)
atom-material-syntax, v0.4.6 (inactive)
atom-material-syntax-dark, v0.2.5 (inactive)
atom-material-ui, v1.3.3 (active)
autocomplete-php, v0.3.7 (inactive)
chester-atom-syntax, v0.1.1 (active)
file-header, v1.9.0 (active)
file-icons, v1.7.18 (active)
file-types, v0.5.4-p1 (active)
fold-search-results, v1.0.5 (inactive)
git-control, v0.8.2 (inactive)
git-plus, v5.16.2 (active)
highlight-selected, v0.11.2 (active)
less-build, v0.1.0 (inactive)
lessc-on-save, v0.4.0 (active)
linter, v1.11.16 (active)
linter-csslint, v1.3.2 (inactive)
linter-htmlhint, v1.3.0 (active)
linter-jshint, v2.1.0 (active)
minimap, v4.24.7 (active)
minimap-highlight-selected, v4.4.0 (inactive)
monokai-seti, v0.7.0 (inactive)
open-recent, v5.0.0 (active)
php-analyser, v0.2.0 (active)
pigments, v0.31.2 (active)
project-manager, v2.9.7 (active)
Remote-FTP, v0.8.6 (active)
save-session, v0.15.7 (active)
seti-icons, v1.3.2 (inactive)
space-tab, v0.4.2 (active)
sync-settings, v0.7.2 (inactive)
tab-switcher, v1.5.3 (active)
todo-show, v1.7.0 (inactive)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.43.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (inactive)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.0 (active)
autocomplete-snippets, v1.11.0 (inactive)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (inactive)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.46.0 (inactive)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.1 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (inactive)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (inactive)
language-clojure, v0.21.0 (inactive)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (inactive)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (inactive)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (inactive)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (inactive)
language-mustache, v0.13.0 (inactive)
language-objective-c, v0.15.1 (inactive)
language-perl, v0.35.0 (inactive)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (inactive)
language-ruby, v0.68.5 (inactive)
language-ruby-on-rails, v0.25.0 (inactive)
language-sass, v0.52.0 (inactive)
language-shellscript, v0.22.3 (inactive)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (inactive)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (inactive)

# Dev
No dev packages
```

**Comment by 50Wliu** [comment]
I _believe_ this has been fixed in Atom 1.9.9, which should be out shortly.
